[ensmallen]
git-tree-sha1 = "9ea11bd3ba51ec6fe03a9987ffbbfa410c9d7e30"

    [[ensmallen.download]]
    sha256 = "9d8e0bbf63874d33db071809db24ff79b71d632058d47467e63f72e5b2b9256a"
    url = "https://github.com/JuliaBinaryWrappers/ensmallen_jll.jl/releases/download/ensmallen-v2.21.0+0/ensmallen.v2.21.0.any.tar.gz"
