# Autogenerated wrapper script for ensmallen_jll for any
JLLWrappers.@generate_wrapper_header("ensmallen")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
